### ISSUE TITLE
Fact updates fail with Puppet 4

### ISSUE THREAD

**Issue by jhg03a** [jorhett/puppet-mcollective#12]
The current cronjob to update facter facts makes the assumption that facter is available in the cron path (different than user path).  With puppet 4, the default binary location has been moved to /opt/puppetlabs/bin.  Therefore when the cronjob tries to execute it can no longer find the facter binary.

**Comment by rjhornsby** [comment]
+1, ran into this issue today deploying mcollective on FOSS puppet.

**Comment by jorhett** [comment]
Good news, I've finally finished my writing and editing work and can work on this stuff this weekend.

**Comment by brahama** [comment]
Still having this issue.

**Comment by jorhett** [comment]
Facter (and other puppet executibles) were added to the default path from version 4.2 onwards. Where are you seeing a problem with this?

I am willing to implement a patch for this, just confused where you're seeing it.

**Comment by rjhornsby** [comment]
cron strips the environment variables, and (usually) reduces $PATH down to only basics like /bin:/usr/bin. Even if /opt/puppetlabs/bin is added to $PATH /etc/profile, I believe that cron effectively ignores it.

AFAIK the (correct?) solution is for crontab files to amend the path environment variable themselves, or for crontab entries to specify the absolute command path.

**Comment by brahama** [comment]
Hey jorhhett...

Centos 7
Puppet 4.5

Subject: Cron <root@iconsulpxu00> facter --puppet --yaml > /etc/puppetlabs/mcollective/facts.yaml.new && ! diff -q /etc/puppetlabs/mcollective/facts.yaml.new /etc/puppetlabs/mcollective/facts.yaml > /dev/null && mv -f /etc/puppetlabs/mcollective/facts.yaml.new /etc/puppetlabs/mcollective/facts.yaml
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=1403>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Date: Mon, 25 Jul 2016 18:30:01 -0300 (ART)
Status: R

/bin/sh: facter: command not found


Seems that the path for cron is not the one in the system.

Thanks!

**Comment by brahama** [comment]
I agree with rjhornsby
There i pasted the resulting cron and why it fails.

Thanks!

**Comment by jorhett** [comment]
I am really sorry. I just found that I stopped receiving notifications on this repo :(  And sadly been so busy I never checked in to find out why it was so quiet. 

If you are still having this problem I'm happy to push a fix. I will be deprecating it soon, but I can push this fix if you still need it.

**Comment by rjhornsby** [comment]
No worries. I don’t presently work with Puppet (at a chef shop now), so this fell off my radar as well. I can’t speak for others, but you don’t need to push anything on my behalf.
