### ISSUE TITLE
templates/server.cfg.erb have a bug about plugin.actionpolicy.default_name

### ISSUE THREAD

**Issue by taejoonmoon** [jorhett/puppet-mcollective#2]
I found a but about plugin.actionpolicy.default_name in templates/server.cfg.erb file.
Let's lookup 90 line. Insteamd of "-" , we need "=".
plugin.actionpolicy.default_name -

 88 <% if( @authorization_default_policy ) then -%>
 89 plugin.actionpolicy.enable_default = 1
 90 plugin.actionpolicy.default_name - <%= @authorization_default_policy -%>
 91 <% else -%>
 92 plugin.actionpolicy.allow_unconfigured = 1
 93 <% end -%>
 94 <% end -%>

**Comment by jorhett** [comment]
Fixed in da19ff208598e53738e2e9262279fb99b7936a0d, thanks for the report!
