### ISSUE TITLE
Conflict with logrotate module

### ISSUE THREAD

**Issue by brahama** [jorhett/puppet-mcollective#20]
If you use a logrotate module, this module gets a conflict trying to declare same resource.

`Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Cannot alias File[logrotate-directory] to ["/etc/logrotate.d"] at /etc/puppetlabs/code/environments/features_profile1/modules/mcollective/manifests/server.pp:321; resource ["File", "/etc/logrotate.d"] already declared at /etc/puppetlabs/code/environments/features_profile1/modules/logrotate/manifests/config.pp:7`

Perhaps removing the file resource which checkks te directory or making some other check.
This of course brings issues i imagine if the directory does not exist. Perhaps adding some manage_logrotate_dir parameter?

Cheers!

**Comment by jorhett** [comment]
I am really sorry. I just found that I never got notifications on this repo :( If you are still having this problem I'm happy to push a fix.

I will be deprecating it soon, but I can push a fix for this if you still need it.
