### ISSUE TITLE
Failed to set full SSL verified mode

### ISSUE THREAD

**Issue by vzabawski** [jorhett/puppet-mcollective#21]
Getting the following error performing `mco` commands.

```
[vagrant@puppetserver production]$ mco ping
warn 2016/08/10 13:55:37: activemq.rb:346:in `rescue in ssl_parameters' Failed to set full SSL verified mode, falling back to unverified: RuntimeError: cert, key and ca has to be supplied for verified SSL mode
puppetserver.example.com                 time=44.92 ms
client.example.com                       time=86.00 ms


---- ping statistics ----
2 replies max: 86.00 min: 44.92 avg: 65.46
```

Here's my **yaml** files. (I changed the extension to upload them).

[common.txt](https://github.com/jorhett/puppet-mcollective/files/417934/common.txt)
[puppetserver.txt](https://github.com/jorhett/puppet-mcollective/files/417909/puppetserver.txt)

**Comment by jorhett** [comment]
Sorry I just found that I never got notifications on this repo :(  If you are still having this problem I'm happy to help.
