### ISSUE TITLE
Default install fails on CentOS 7 for Puppet 4.x Open Source (havent tried 6 yet)

### ISSUE THREAD

**Issue by devoncustard** [jorhett/puppet-mcollective#24]
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install activemq' returned 1: Error: Nothing to do
Error: /Stage[main]/Mcollective::Middleware/Package[activemq]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install activemq' returned 1: Error: Nothing to do

ActiveMq doesn't appear to be included in the CentOS repos found in a minimal install. I worked around the same issue for rubygem-stomp by installing the epel-release package, just need to find a repo for ActiveMq. 

Could probably do with amending your docs to mention the requirements for epel-release and a repo for ActiveMQ

**Comment by devoncustard** [comment]
Ok from what i can tell, puppetlabs provide ActiveMq in the older repos for Puppet 3.x etc but since the migration to 4 they no longer provide it. Presumably because its part of their nice AIO installer. Which is great if you are running PE but not if you are a freeloader like me ;)

This has a major deja vu feeling about this so its probably not the first time ive tripped over this issue so forgive me if its old news.

**Comment by devoncustard** [comment]
As a workaround I added the repo to yum and yay installed fine. Not sure how comfortable I am having both the 3.x and 4.x repos installed at the same time, some thing will probably break but it did allow me to get module to work.

**Comment by tracphil** [comment]
@devoncustard Isn't this what you are looking for https://yum.puppetlabs.com/el/7/dependencies/x86_64/

**Comment by devoncustard** [comment]
I did not know about that repo. :) I'd still like to suggest that the module could do with documenting that repo as a dependency. Or at least mention that the module wont work "out of the box" at least for Puppet 4 OSS.

Either way thanks for pointing me in the right direction.

**Comment by tracphil** [comment]
Agreed. However, I think this repo is pretty much dead and the author has moved on to other things now that the book is out. Maybe it will get some love when an updated version of the book is required.

**Comment by jorhett** [comment]
Actually, I had just found that Github wasn't sending me notifications for this repo and fixed it :(  I would have responded if I had known there were issues here.

If this is actively breaking you I'll fix it. However in the long term this repo is being deprecated in favor of choria https://forge.puppet.com/choria/choria and I'd advise deploying that if you can.
