### ISSUE TITLE
Syntax wrong in jetty-realm.properties.erb

### ISSUE THREAD

**Issue by devoncustard** [jorhett/puppet-mcollective#6]
Im seeing this when i set the use_jmx and jetty_password values.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template mcollective/jetty-realm.properties.erb:
  Filepath: /etc/puppetlabs/code/environments/production/modules/mcollective/templates/jetty-realm.properties.erb
  Line: 20
  Detail: undefined local variable or method `jetty_password' for #<Puppet::Parser::TemplateWrapper:0x1b7a6455>
 at /etc/puppetlabs/code/environments/production/modules/mcollective/manifests/middleware.pp:195:18 on node borg.cha.rbxd.ds

Im not an expert in puppet but im pretty certain

admin: <%= jetty_password -%>, admin

should be

admin: <%= @jetty_password -%>, admin
.

**Comment by jorhett** [comment]
Thanks! Fixed in 18e203a9832cf0cb3cebdca0b6c003cf7d927653
