### ISSUE TITLE
Question: Is mcollective::hosts required?

### ISSUE THREAD

**Issue by chad-upton** [jorhett/puppet-mcollective#7]
Reason I ask, is we want mcollective on every host.  

Specifying each of them here wouldn't work in an autoscaling scenario.

Does this module currently support this?

**Comment by jorhett** [comment]
That parameter should probably be renamed middleware_hosts. It should contains a list of ActiveMQ or RabbitMQ (middleware) servers that every node should connect to. This will have to be a static list.

There is no place and no need to specify every end node, only the middleware that connects all nodes.

**Comment by chad-upton** [comment]
That makes a lot more sense, thanks sir!
