### ISSUE TITLE
SSHkey plugin missing

### ISSUE THREAD

**Issue by jhg03a** [jorhett/puppet-mcollective#8]
Your module references the SSHKey module, but the code to obtain and deploy it is missing.

**Comment by jorhett** [comment]
It's spelled out in the book why I consider the sshkey module to be a security problem. And including it would add significantly more dependencies for people who don't want to use it. Therefore it's optional.

**Comment by jhg03a** [comment]
Would you consider sharing the brief summary of your reasoning for those who don't currently own your book?

**Comment by jorhett** [comment]
MCollective is a framework for which plugins are installed. Each plugin can be installed separately, and will have its own dependencies. So your question really becomes "why didn't you bundle X plugin in?" and the answer is that I didn't bundle U, V, W, Y, or Z either ;)

This module installs the framework, and only the plugins which are included with the framework. It can also be used to install configure and enable external plugins that you choose to install.
