### ISSUE TITLE
Client trusted SSL Connection broken

### ISSUE THREAD

**Issue by jhg03a** [jorhett/puppet-mcollective#9]
> mco ping
> info 2016/01/20 16:45:07: config.rb:167:in `loadconfig' The Marionette Collective version 2.8.6 started by > ./mco using config file /etc/puppetlabs/mcollective/client.cfg
> info 2016/01/20 16:45:07: activemq.rb:211:in`initialize' ActiveMQ connector initialized.  Using stomp-gem 1.3.3
> error 2016/01/20 16:45:07: activemq.rb:349:in `rescue in ssl_parameters' Failed to set full SSL verified mode: RuntimeError: cert, key and ca has to be supplied for verified SSL mode
> 
> The ping application failed to run, use -v for full error backtrace details: Could not connect to ActiveMQ Server: cert, key and ca has to be supplied for verified SSL mode

It would appear you've [correctly set the cert, key, and ca in server.cfg.erb](https://github.com/jorhett/puppet-mcollective/blob/91a72dffdc3df0c79662d6291b86840194d3c99f/templates/server.cfg.erb#L29-L32), but missed setting the same information in the client configuration when using the trusted ssl connector type.

**Comment by vzabauski** [comment]
I have a similar problem.
```
[vagrant@puppetserver production]$ mco ping
warn 2016/08/10 13:55:37: activemq.rb:346:in `rescue in ssl_parameters' Failed to set full SSL verified mode, falling back to unverified: RuntimeError: cert, key and ca has to be supplied for verified SSL mode
puppetserver.example.com                 time=44.92 ms
client.example.com                       time=86.00 ms


---- ping statistics ----
2 replies max: 86.00 min: 44.92 avg: 65.46
```
Here's my **yaml** files and **activemq.xml** (I changed the extension to upload them).
[activemq.txt](https://github.com/jorhett/puppet-mcollective/files/411257/activemq.txt)


[common.txt](https://github.com/jorhett/puppet-mcollective/files/411254/common.txt)
[puppetserver.txt](https://github.com/jorhett/puppet-mcollective/files/411253/puppetserver.txt)

**Comment by jorhett** [comment]
I would hope that you're using choria by now ;-)
